language: node_js
env: TIMEOUT=10000 # Travis machines are slow so we set the TIMEOUT to be big
install:
  - npm cache clean
  - npm install
node_js:
  - "0.11"
  - "0.10"
os:
  - linux
  # - osx # Node.js on OSX is not yet supported by TravisCI
  # - windows # Windows is not yet supported by TravisCI